
file stringout_param.template
{
    pattern
    {  param        port_drvr_string  pini  val}
    {  GetIDN				PI_GET_IDN				NO		"*IDN?"}
} 

file waveform_param.template
{
    pattern
    {  param      	port_drvr_string  pini  nelm}
    {  SendCmnds		PI_SEND_COMMANDS		NO		5000	}
    
}



file ao_param.template
{
    pattern
    {  param            param_type     port_drvr_string   pini  drvl			drvh			val}
    {  SetMarker				asynFloat64    PI_SET_MARKER		NO		-9999999	9999999			0}
    {  SetVelo				asynFloat64    	 PI_SET_VELO			NO		0					9999999			0}

    {  MarkerStart			asynFloat64    PI_MARKER_START		NO		-9999999	9999999			0}
    {  MarkerStop				asynFloat64    PI_MARKER_STOP		NO		-9999999	9999999			0}

    {  ScanStart				asynFloat64    PI_SCAN_START		NO		-9999999	9999999			0}
    {  ScanStop					asynFloat64    PI_SCAN_STOP		NO		-9999999	9999999			0}
    
    {  SetStartupPos		asynFloat64    PI_SET_STARTUP_POS		NO		-9999999	9999999			0}
    {  OutputVolt				asynFloat64    PI_OUTPUT_VOLT		NO		-20	120			0}
    
    {  ForceDoneWaitTime	asynFloat64    PI_FORCE_DONE_WAIT_TIME		NO		0	10			0}
    
    
    {  DigFltBWidth			asynFloat64    PI_DIGFILT_BWIDTH	NO		0	5000			0}
    {  DigFltParm1				asynFloat64    PI_DIGFILT_PARM1		NO		0	9999999			0}
    {  DigFltParm2				asynFloat64    PI_DIGFILT_PARM2		NO		0	9999999			0}
    {  DigFltParm3				asynFloat64    PI_DIGFILT_PARM3		NO		0	9999999			0}
    {  DigFltParm4				asynFloat64    PI_DIGFILT_PARM4		NO		0	9999999			0}
    {  DigFltParm5				asynFloat64    PI_DIGFILT_PARM5		NO		0	9999999			0}
    
    {  CapSensBParm				asynFloat64    PI_CAPSENS_B_PARM		YES		-9999999	9999999			-17.25}
    {  CapSensMParm				asynFloat64    PI_CAPSENS_M_PARM		YES		-9999999	9999999			-0.9943}
    
    {  TrigOutput				asynInt32    PI_TRIG_OUTPUT		YES		1		8			1}
    {  XAxisId					asynInt32    PI_X_AXIS_ID			YES		1		4			3}
    
}



file ai_param.template
{
    pattern
    {  param            param_type     port_drvr_string   	pini  }
#    {  OutputVolt				asynFloat64   PI_OUTPUT_VOLT	YES		}
    {  AdcSensor				asynFloat64    	PI_ADC_SENSOR	YES		}
    {  CapSensor				asynFloat64    	PI_CAP_SENSOR	YES		}
    
}


# here param_type refers to the readback type
file mbbo_param.template
{
    pattern
    {  param  param_type     port_drvr_string   pini 	zrst						zrvl	onst					onvl	twst	twvl	thst	thvl	frst	frvl	fvst	fvvl	sxst	sxvl	svst	svvl	eist	eivl	nist	nivl	test	tevl	elst	elvl	tvst	tvvl	ttst	ttvl	ftst	ftvl	ffst	ffvl	}
    {  Mode   asynInt32   	 PI_MODE   					YES		"NORMAL"				0			"LINE_UNIDIR"	1			"LINE_BIDIR"		2		"POINT"		3		"COARSE"		4		"SCAN_START"		5		""		6		""		7		""		8		""		9		""		10		""		11		""		12		""		13		""		14		""		15	}
#define CTO_TRIGMODE_POSDIST 	0
#define CTO_TRIGMODE_ONTRGT 	2
#define CTO_TRIGMODE_MINMAX 	3
#define CTO_TRIGMODE_GENTRIG 	4    
    {  CTO    asynInt32   	 			PI_TRIG_OUTPUT_SEL YES		"POSITION_DIST"				0			"ON_TARGET"	2			"MIN_MAX"		3		"GENERATOR"		4		""		5		""		6		""		7		""		8		""		9		""		10		""		11		""		12		""		13		""		14		""		15		""		16	}
    {  DigFltType    asynInt32   	 PI_DIGFILT_TYPE NO		"Type 0"	0			"Type 1"		1			"Type 2"		2		"Type 3"		3		""		4		""		5		""		6		""		7		""		8		""		9		""		10		""		11		""		12		""		13		""		14		""		15	}
    {  DigFltOrder   asynInt32   	 PI_DIGFILT_ORDER NO		"0"				0			"1"		1			"2"		2		"3"		3		""		4		""		5		""		6		""		7		""		8		""		9		""		10		""		11		""		12		""		13		""		14		""		15	}
		{  ForceDone		 asynInt32   	 PI_FORCE_DONE  YES		"NORMAL"	0 	"FORCED"	1   "INTERNAL_TIMED"		2		"3"		3		""		4		""		5		""		6		""		7		""		8		""		9		""		10		""		11		""		12		""		13		""		14		""		15	}
}



# here param_type refers to the readback type
file bo_param.template
{
    pattern
    {  param  				param_type     port_drvr_string   	pini 	znam		onam	high}
    {  ServoPower    	asynInt32   	 PI_POWER   		NO		"OFF"		"ON"	0.0}
    {  ReInitialize  	asynInt32   	 PI_RE_INITIALIZE   		NO		"OFF"		"ON"	0.0}
#    {  CoarseStatus    				asynInt32   	 COARSE_STATUS   		NO		"STOPPED"		"MOVING"	0.0}
		{  AutoZero    		asynInt32   	 PI_AUTO_ZERO   									NO		"OFF"		"ON"	0.0}
		{  SelectEncoder  asynInt32   	 PI_SELECT_ENCODER_SOURCE   			NO		"Capacitive"		"Quadrature"	0.0}
		{  SelectOutputDir  asynInt32   	 PI_SELECT_OUTPUT_DIRECTION   	YES		"POS"		"NEG"	0.0}
#		{  ForceDone		  asynInt32   	 PI_FORCE_DONE   	YES		"NORMAL"		"FORCED"	0.0}
		{  ZeroADSensor  	asynInt32   	 PI_ZERO_AD_SENSOR	NO		"OFF"		"ON"	0.0}
		{  VoltRngWarn  	asynInt32   	 PI_VOLT_RANGE_WARNING	NO		"GOOD"		"WARNING"	0.0}
		{  ResetVoltRngWarn  	asynInt32  PI_RESET_VOLT_RANGE_WARNING	NO		"OFF"		"ON"	0.2}
		{  ServoOffAndCntr  	asynInt32  PI_SERVO_OFF_AND_CENTER	NO		"OFF"		"ON"	0.2}
		
			
}


file e712Cntrllr_bo_param.template
{
    pattern
    {  param  				param_type     port_drvr_string   	pini 	znam		onam	high}

		{  WaveGen1Status  	asynInt32  PI_WAVEGEN_1_STATUS	YES		"STOPPED"		"RUNNING"	0.0}
		{  WaveGen2Status  	asynInt32  PI_WAVEGEN_2_STATUS	YES		"STOPPED"		"RUNNING"	0.0}
		{  WaveGen3Status  	asynInt32  PI_WAVEGEN_3_STATUS	YES		"STOPPED"		"RUNNING"	0.0}
		{  WaveGen4Status  	asynInt32  PI_WAVEGEN_4_STATUS	YES		"STOPPED"		"RUNNING"	0.0}
		
		{  GetWavTbl1  		asynInt32  		PI_GET_WVTBL_1		NO		"OFF"		"ON"	0.2}
		{  GetWavTbl2  		asynInt32  		PI_GET_WVTBL_2		NO		"OFF"		"ON"	0.2}
		{  GetWavTbl3  		asynInt32  		PI_GET_WVTBL_3		NO		"OFF"		"ON"	0.2}
		{  GetWavTbl4  		asynInt32  		PI_GET_WVTBL_4		NO		"OFF"		"ON"	0.2}
		
		{  GetDDLTbl1  		asynInt32  		PI_GET_DDLTBL_1		NO		"OFF"		"ON"	0.2}
		{  GetDDLTbl2  		asynInt32  		PI_GET_DDLTBL_2		NO		"OFF"		"ON"	0.2}
		{  GetDDLTbl3  		asynInt32  		PI_GET_DDLTBL_3		NO		"OFF"		"ON"	0.2}
		{  GetDDLTbl4  		asynInt32  		PI_GET_DDLTBL_4		NO		"OFF"		"ON"	0.2}
		
		{  GetTrigTbl  		asynInt32  		PI_GET_TRIG_TBL		NO		"OFF"		"ON"	0.2}
		
		{  ClearDDLTbl1  		asynInt32  	PI_CLR_DDLTBL_1		NO		"OFF"		"ON"	0.2}
		{  ClearDDLTbl2  		asynInt32  	PI_CLR_DDLTBL_2		NO		"OFF"		"ON"	0.2}
		{  ClearDDLTbl3  		asynInt32  	PI_CLR_DDLTBL_3		NO		"OFF"		"ON"	0.2}
		{  ClearDDLTbl4  		asynInt32  	PI_CLR_DDLTBL_4		NO		"OFF"		"ON"	0.2}
}

file dbl_waveform_param.template
{
    pattern
    {  param      	port_drvr_string  pini  nelm}
    {  WaveTbl1			PI_WAVETBL_1				NO		262144	}
    {  WaveTbl2			PI_WAVETBL_2				NO		262144	}
    {  WaveTbl3			PI_WAVETBL_3				NO		262144	}
    {  WaveTbl4			PI_WAVETBL_4				NO		262144	}
    
    {  DDLTbl1			PI_DDLTBL_1				NO		262144	}
    {  DDLTbl2			PI_DDLTBL_2				NO		262144	}
    {  DDLTbl3			PI_DDLTBL_3				NO		262144	}
    {  DDLTbl4			PI_DDLTBL_4				NO		262144	}
    
    {  TrigTbl			PI_TRIG_TBL				NO		262144	}
    
}

