TOP=../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

#==================================================
# Build an IOC support library
#USR_CFLAGS += -DDEBUG  /Zi 
#USR_CPPFLAGS += -DDEBUG /Zi -IC:\Continuum\Anaconda2\include 
#USR_LDFLAGS += /INCREMENTAL:NO /OPT:REF /OPT:ICF /LIBPATH:C:\Continuum\Anaconda2\libs

USR_CPPFLAGS += -I/home/beamline/tools/anaconda3/include/python3.7m -Wno-unused-variable
USR_LDFLAGS += -L/home/beamline/tools/anaconda3/lib -Wno-unused-variable




LIBRARY_IOC += PI_E712Support

# motorRecord.h will be created from motorRecord.dbd
# install devMotorSoft.dbd into <top>/dbd
DBD += PI_E712Support.dbd

# The following are compiled and added to the Support library
PI_E712Support_SRCS += PIE712Controller.cpp


#PI_E712Support_SRCS += PIGCSController.cpp
#PI_E712Support_SRCS += PIGCSMotorController.cpp
#PI_E712Support_SRCS += PIGCSPiezoController.cpp
#PI_E712Support_SRCS += PIE517Controller.cpp
#PI_E712Support_SRCS += PIE755Controller.cpp
#PI_E712Support_SRCS += PIHexapodController.cpp
#PI_E712Support_SRCS += PIGCS2_HexapodController.cpp
#PI_E712Support_SRCS += PIC702Controller.cpp
PI_E712Support_SRCS += translateerror.c
PI_E712Support_SRCS += PIInterface.cpp
#PI_E712Support_SRCS += PIDaisyChainInterface.cpp

PI_E712Support_SRCS += load_param_file.cpp

PI_E712Support_LIBS += motor
PI_E712Support_LIBS += asyn
PI_E712Support_LIBS += $(EPICS_BASE_IOC_LIBS)

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

