/* C code for program load_param_file, generated by snc from ../load_param_file.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 5 "../load_param_file.st"
extern void load_parameter_file(char *fname);

/* Variable declarations */
# line 3 "../load_param_file.st"
static	char parm_filename[40];


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init_load" in state set "_load_file" ******/

/* Entry function for state "init_load" in state set "_load_file" */
static void seqg_entry__load_file_0_init_load(SS_ID seqg_env)
{
# line 12 "../load_param_file.st"
	if (seq_macValueGet(seqg_env, "param_file") != 0)
	{
# line 14 "../load_param_file.st"
		sprintf(parm_filename, "%s", seq_macValueGet(seqg_env, "param_file"));
	}
	else
	{
# line 16 "../load_param_file.st"
		printf("load_param_file: NO PARAM FILE SPECIFIED!!!");
# line 17 "../load_param_file.st"
		exit(1);
	}
# line 19 "../load_param_file.st"
	printf("param_file = %s\n", parm_filename);
}

/* Event function for state "init_load" in state set "_load_file" */
static seqBool seqg_event__load_file_0_init_load(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 23 "../load_param_file.st"
	if (seq_delay(seqg_env, 1.0))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init_load" in state set "_load_file" */
static void seqg_action__load_file_0_init_load(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "wait_for_load_start" in state set "_load_file" ******/

/* Event function for state "wait_for_load_start" in state set "_load_file" */
static seqBool seqg_event__load_file_0_wait_for_load_start(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 35 "../load_param_file.st"
	if (1)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "wait_for_load_start" in state set "_load_file" */
static void seqg_action__load_file_0_wait_for_load_start(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 37 "../load_param_file.st"
			printf("calling load_parameter_file(%s)\n", parm_filename);
		}
		return;
	}
}

/****** Code for state "finish" in state set "_load_file" ******/

/* Event function for state "finish" in state set "_load_file" */
static seqBool seqg_event__load_file_0_finish(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 53 "../load_param_file.st"
	if (seq_delay(seqg_env, 1.0))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "finish" in state set "_load_file" */
static void seqg_action__load_file_0_finish(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 55 "../load_param_file.st"
			printf("Done executing\n");
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* No channel definitions */
#define seqg_chans 0

/* Event masks for state set "_load_file" */
static const seqMask seqg_mask__load_file_0_init_load[] = {
	0x00000000,
};
static const seqMask seqg_mask__load_file_0_wait_for_load_start[] = {
	0x00000000,
};
static const seqMask seqg_mask__load_file_0_finish[] = {
	0x00000000,
};

/* State table for state set "_load_file" */
static seqState seqg_states__load_file[] = {
	{
	/* state name */        "init_load",
	/* action function */   seqg_action__load_file_0_init_load,
	/* event function */    seqg_event__load_file_0_init_load,
	/* entry function */    seqg_entry__load_file_0_init_load,
	/* exit function */     0,
	/* event mask array */  seqg_mask__load_file_0_init_load,
	/* state options */     (0)
	},
	{
	/* state name */        "wait_for_load_start",
	/* action function */   seqg_action__load_file_0_wait_for_load_start,
	/* event function */    seqg_event__load_file_0_wait_for_load_start,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask__load_file_0_wait_for_load_start,
	/* state options */     (0)
	},
	{
	/* state name */        "finish",
	/* action function */   seqg_action__load_file_0_finish,
	/* event function */    seqg_event__load_file_0_finish,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask__load_file_0_finish,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "_load_file",
	/* states */            seqg_states__load_file,
	/* number of states */  3
	},
};

/* Program table (global) */
seqProgram load_param_file = {
	/* magic number */      2002006,
	/* program name */      "load_param_file",
	/* channels */          seqg_chans,
	/* num. channels */     0,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};
# line 62 "../load_param_file.st"

# 96 "../load_param_file.st"


/* Register sequencer commands and program */
#include "epicsExport.h"
static void load_param_fileRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&load_param_file);
}
epicsExportRegistrar(load_param_fileRegistrar);
